### ISSUE TITLE
CUDA 11.4 can not compile

### ISSUE THREAD

**Issue by ax7e** [NVIDIA/nvbench#111]
The code uses `CUpti_Profiler_GetCounterAvailability_Params`， which does not exist in cupti 11.4

**Comment by aaronmondal** [comment]
I may be blind, but the [release notes for CUPTI](https://docs.nvidia.com/cupti/release_notes.html#release_notes_11.4) don't seem to mention any changes to that symbol and links to the cupti docs seem to link to link to cupti 11.8, even for older CUDA releases. This may be a "bug" in the documentation.

It seems to work with 11.8.

**Comment by ax7e** [comment]
So you neither search the code nor try reproducing the bug, just gossiping here. What's the point of doing so?

**Comment by ax7e** [comment]
> I may be blind, but the [release notes for CUPTI](https://docs.nvidia.com/cupti/release_notes.html#release_notes_11.4) don't seem to mention any changes to that symbol and links to the cupti docs seem to link to link to cupti 11.8, even for older CUDA releases. This may be a "bug" in the documentation.
> 
> It seems to work with 11.8.

 So you neither search the code nor try reproducing the bug, just gossiping here. What's the point of doing so?

**Comment by ax7e** [comment]
Adding the errors.
```c++
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx: In member function ‘void nvbench::detail::cupti_profiler::initialize_availability_image()’:
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:128:3: error: ‘CUpti_Profiler_GetCounterAvailability_Params’ was not declared in this scope; did you mean ‘CUpti_Profiler_FlushCounterData_Params’?  128 |   CUpti_Profiler_GetCounterAvailability_Params params{};
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |   CUpti_Profiler_FlushCounterData_Params
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:130:3: error: ‘params’ was not declared in this scope
  130 |   params.structSize = CUpti_Profiler_GetCounterAvailability_Params_STRUCT_SIZE;
      |   ^~~~~~
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:130:23: error: ‘CUpti_Profiler_GetCounterAvailability_Params_STRUCT_SIZE’ was not declared in this scope; did you mean ‘CUpti_Profiler_FlushCounterData_Params_STRUCT_SIZE’?
  130 |   params.structSize = CUpti_Profiler_GetCounterAvailability_Params_STRUCT_SIZE;
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                       CUpti_Profiler_FlushCounterData_Params_STRUCT_SIZE
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:133:14: error: ‘cuptiProfilerGetCounterAvailability’ was not declared in this scope
  133 |   cupti_call(cuptiProfilerGetCounterAvailability(&params));
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx: At global scope:
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:154:3: error: ‘NVPW_MetricsEvaluator’ does not name a type
  154 |   NVPW_MetricsEvaluator *evaluator_ptr;
      |   ^~~~~~~~~~~~~~~~~~~~~
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:157:37: error: expected ‘)’ before ‘*’ token
  157 |   eval_request(NVPW_MetricsEvaluator *evaluator_ptr, const std::string &metric_name)
      |               ~                     ^~
      |                                     )
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:195:3: error: ‘NVPW_MetricEvalRequest’ does not name a type
  195 |   NVPW_MetricEvalRequest request;
      |   ^~~~~~~~~~~~~~~~~~~~~~
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx: In member function ‘std::vector<const char*> nvbench::detail::{anonymous}::eval_request::get_raw_dependencies()’:
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:176:5: error: ‘NVPW_MetricsEvaluator_GetMetricRawDependencies_Params’ was not declared in this scope
  176 |     NVPW_MetricsEvaluator_GetMetricRawDependencies_Params params{};
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:178:5: error: ‘params’ was not declared in this scope
  178 |     params.structSize          = NVPW_MetricsEvaluator_GetMetricRawDependencies_Params_STRUCT_SIZE;
      |     ^~~~~~
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:178:34: error: ‘NVPW_MetricsEvaluator_GetMetricRawDependencies_Params_STRUCT_SIZE’ was not declared in this scope; did you mean ‘NVPW_MetricsContext_GetMetricNames_Begin_Params_STRUCT_SIZE’?
  178 |     params.structSize          = NVPW_MetricsEvaluator_GetMetricRawDependencies_Params_STRUCT_SIZE;
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                  NVPW_MetricsContext_GetMetricNames_Begin_Params_STRUCT_SIZE
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:179:34: error: ‘evaluator_ptr’ was not declared in this scope
  179 |     params.pMetricsEvaluator   = evaluator_ptr;
      |                                  ^~~~~~~~~~~~~
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:180:35: error: ‘request’ was not declared in this scope
  180 |     params.pMetricEvalRequests = &request;
      |                                   ^~~~~~~
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:182:42: error: ‘NVPW_MetricEvalRequest_STRUCT_SIZE’ was not declared in this scope
  182 |     params.metricEvalRequestStructSize = NVPW_MetricEvalRequest_STRUCT_SIZE;
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:183:49: error: ‘NVPW_MetricEvalRequest’ was not declared in this scope
  183 |     params.metricEvalRequestStrideSize = sizeof(NVPW_MetricEvalRequest);
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:185:15: error: ‘NVPW_MetricsEvaluator_GetMetricRawDependencies’ was not declared in this scope
  185 |     nvpw_call(NVPW_MetricsEvaluator_GetMetricRawDependencies(&params));
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx: At global scope:
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:201:3: error: ‘NVPW_MetricsEvaluator’ does not name a type
  201 |   NVPW_MetricsEvaluator *evaluator_ptr;
      |   ^~~~~~~~~~~~~~~~~~~~~
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:255:26: error: ‘NVPW_MetricsEvaluator’ does not name a type
  255 |   [[nodiscard]] operator NVPW_MetricsEvaluator *() const { return evaluator_ptr; }
      |                          ^~~~~~~~~~~~~~~~~~~~~
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx: In constructor ‘nvbench::detail::{anonymous}::metric_evaluator::metric_evaluator(const string&, const uint8_t*, const uint8_t*, std::size_t)’:
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:210:5: error: ‘NVPW_CUDA_MetricsEvaluator_CalculateScratchBufferSize_Params’ was not declared in this scope
  210 |     NVPW_CUDA_MetricsEvaluator_CalculateScratchBufferSize_Params scratch_buffer_param{};
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:212:5: error: ‘scratch_buffer_param’ was not declared in this scope; did you mean ‘scratch_buffer’?
  212 |     scratch_buffer_param.structSize =
      |     ^~~~~~~~~~~~~~~~~~~~
      |     scratch_buffer
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:213:7: error: ‘NVPW_CUDA_MetricsEvaluator_CalculateScratchBufferSize_Params_STRUCT_SIZE’ was not declared in this scope
  213 |       NVPW_CUDA_MetricsEvaluator_CalculateScratchBufferSize_Params_STRUCT_SIZE;
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:217:15: error: ‘NVPW_CUDA_MetricsEvaluator_CalculateScratchBufferSize’ was not declared in this scope
  217 |     nvpw_call(NVPW_CUDA_MetricsEvaluator_CalculateScratchBufferSize(&scratch_buffer_param));
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:221:5: error: ‘NVPW_CUDA_MetricsEvaluator_Initialize_Params’ was not declared in this scope
  221 |     NVPW_CUDA_MetricsEvaluator_Initialize_Params evaluator_params{};
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:223:5: error: ‘evaluator_params’ was not declared in this scope
  223 |     evaluator_params.structSize        = NVPW_CUDA_MetricsEvaluator_Initialize_Params_STRUCT_SIZE;
      |     ^~~~~~~~~~~~~~~~
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:223:42: error: ‘NVPW_CUDA_MetricsEvaluator_Initialize_Params_STRUCT_SIZE’ was not declared in this scope; did you mean ‘NVPW_CUDA_MetricsContext_Create_Params_STRUCT_SIZE’?
  223 |     evaluator_params.structSize        = NVPW_CUDA_MetricsEvaluator_Initialize_Params_STRUCT_SIZE;
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                          NVPW_CUDA_MetricsContext_Create_Params_STRUCT_SIZE
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:231:15: error: ‘NVPW_CUDA_MetricsEvaluator_Initialize’ was not declared in this scope
  231 |     nvpw_call(NVPW_CUDA_MetricsEvaluator_Initialize(&evaluator_params));
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:233:5: error: ‘evaluator_ptr’ was not declared in this scope
  233 |     evaluator_ptr = evaluator_params.pMetricsEvaluator;
      |     ^~~~~~~~~~~~~
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx: In destructor ‘nvbench::detail::{anonymous}::metric_evaluator::~metric_evaluator()’:
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:241:7: error: ‘NVPW_MetricsEvaluator_Destroy_Params’ was not declared in this scope; did you mean ‘NVPW_MetricsContext_Destroy_Params’?
  241 |       NVPW_MetricsEvaluator_Destroy_Params params{};
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |       NVPW_MetricsContext_Destroy_Params
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:243:7: error: ‘params’ was not declared in this scope
  243 |       params.structSize        = NVPW_MetricsEvaluator_Destroy_Params_STRUCT_SIZE;
      |       ^~~~~~
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:243:34: error: ‘NVPW_MetricsEvaluator_Destroy_Params_STRUCT_SIZE’ was not declared in this scope; did you mean ‘NVPW_MetricsContext_Destroy_Params_STRUCT_SIZE’?
  243 |       params.structSize        = NVPW_MetricsEvaluator_Destroy_Params_STRUCT_SIZE;
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                  NVPW_MetricsContext_Destroy_Params_STRUCT_SIZE
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:244:34: error: ‘evaluator_ptr’ was not declared in this scope
  244 |       params.pMetricsEvaluator = evaluator_ptr;
      |                                  ^~~~~~~~~~~~~
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:246:17: error: ‘NVPW_MetricsEvaluator_Destro
’ was not declared in this scope; did you mean ‘NVPW_MetricsContext_Destroy’?
  246 |       nvpw_call(NVPW_MetricsEvaluator_Destroy(&params));
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                 NVPW_MetricsContext_Destroy
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx: In member function ‘nvbench::detail::{anonymous}::eval_request nvbench::detail::{anonymous}::metric_evaluator::create_request(const string&)’:
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:252:13: error: ‘evaluator_ptr’ was not declared in this scope
  252 |     return {evaluator_ptr, metric_name};
      |             ^~~~~~~~~~~~~
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:252:39: error: could not convert ‘{<expression error>, metric_name}’ from ‘<brace-enclosed initializer list>’ to ‘nvbench::detail::{anonymous}::eval_request’
  252 |     return {evaluator_ptr, metric_name};
      |                                       ^
      |                                       |
      |                                       <brace-enclosed initializer list>
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx: In member function ‘void nvbench::detail::{anonymous}::metrics_config::create(const string&, const uint8_t*)’:
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:303:5: error: ‘NVPW_CUDA_RawMetricsConfig_Create_V2_Params’ was not declared in this scope; did you mean ‘NVPW_CUDA_RawMetricsConfig_Create_Params’?
  303 |     NVPW_CUDA_RawMetricsConfig_Create_V2_Params params{};
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     NVPW_CUDA_RawMetricsConfig_Create_Params
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:305:5: error: ‘params’ was not declared in this scope
  305 |     params.structSize                = NVPW_CUDA_RawMetricsConfig_Create_V2_Params_STRUCT_SIZE;
      |     ^~~~~~
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:305:40: error: ‘NVPW_CUDA_RawMetricsConfig_Create_V2_Params_STRUCT_SIZE’ was not declared in this scope; did you mean ‘NVPW_CUDA_RawMetricsConfig_Create_Params_STRUCT_SIZE’?
  305 |     params.structSize                = NVPW_CUDA_RawMetricsConfig_Create_V2_Params_STRUCT_SIZ
;
      |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                        NVPW_CUDA_RawMetricsConfig_Create_Params_STRUCT_SIZE
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:310:15: error: ‘NVPW_CUDA_RawMetricsConfig_Create_V2’ was not declared in this scope; did you mean ‘NVPW_CUDA_RawMetricsConfig_Create’?
  310 |     nvpw_call(NVPW_CUDA_RawMetricsConfig_Create_V2(&params));
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |               NVPW_CUDA_RawMetricsConfig_Create
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx: In member function ‘void nvbench::detail::{anonymous}::metrics_config::set_availability_image(const uint8_t*)’:
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:318:5: error: ‘NVPW_RawMetricsConfig_SetCounterAvailability_Params’ was not declared in this scope; did you mean ‘NVPW_RawMetricsConfig_GetConfigImage_Params’?
  318 |     NVPW_RawMetricsConfig_SetCounterAvailability_Params params{};
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     NVPW_RawMetricsConfig_GetConfigImage_Params
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:320:5: error: ‘params’ was not declared in this scope
  320 |     params.structSize        = NVPW_RawMetricsConfig_SetCounterAvailability_Params_STRUCT_SIZE;
      |     ^~~~~~
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:320:32: error: ‘NVPW_RawMetricsConfig_SetCounterAvailability_Params_STRUCT_SIZE’ was not declared in this scope; did you mean ‘NVPW_RawMetricsConfig_GetConfigImage_Params_STRUCT_SIZE’?
  320 |     params.structSize        = NVPW_RawMetricsConfig_SetCounterAvailability_Params_STRUCT_SIZ
;
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                NVPW_RawMetricsConfig_GetConfigImage_Params_STRUCT_SIZE
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:324:15: error: ‘NVPW_RawMetricsConfig_SetCounterAvailability’ was not declared in this scope
  324 |     nvpw_call(NVPW_RawMetricsConfig_SetCounterAvailability(&params));
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx: In constructor ‘nvbench::detail::{anonymous}::counter_data_builder::counter_data_builder(const string&, const uint8_t*)’:
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:440:5: error: ‘NVPW_CUDA_CounterDataBuilder_Create_Params’ was not declared in this scope; did you mean ‘NVPW_CounterDataBuilder_Create_Params’?
  440 |     NVPW_CUDA_CounterDataBuilder_Create_Params params{};
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     NVPW_CounterDataBuilder_Create_Params
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:442:5: error: ‘params’ was not declared in this scope
  442 |     params.structSize                = NVPW_CUDA_CounterDataBuilder_Create_Params_STRUCT_SIZE;      |     ^~~~~~
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:442:40: error: ‘NVPW_CUDA_CounterDataBuilder_Create_Params_STRUCT_SIZE’ was not declared in this scope; did you mean ‘NVPW_CounterDataBuilder_Create_Params_STRUCT_SIZE’?
  442 |     params.structSize                = NVPW_CUDA_CounterDataBuilder_Create_Params_STRUCT_SIZE;      |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                        NVPW_CounterDataBuilder_Create_Params_STRUCT_SIZE
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:446:15: error: ‘NVPW_CUDA_CounterDataBuilder_Create’ was not declared in this scope; did you mean ‘NVPW_CounterDataBuilder_Create’?
  446 |     nvpw_call(NVPW_CUDA_CounterDataBuilder_Create(&params));
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |               NVPW_CounterDataBuilder_Create
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx: In member function ‘std::vector<double> nvbench::detail::cupti_profiler::get_counter_values()’:
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:723:7: error: ‘NVPW_MetricsEvaluator_SetDeviceAttributes_Params’ was not declared in this scope
  723 |       NVPW_MetricsEvaluator_SetDeviceAttributes_Params params{};
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:725:7: error: ‘params’ was not declared in this scope
  725 |       params.structSize           = NVPW_MetricsEvaluator_SetDeviceAttributes_Params_STRUCT_SIZE;
      |       ^~~~~~
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:725:37: error: ‘NVPW_MetricsEvaluator_SetDeviceAttributes_Params_STRUCT_SIZE’ was not declared in this scope
  725 |       params.structSize           = NVPW_MetricsEvaluator_SetDeviceAttributes_Params_STRUCT_SIZE;
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:730:17: error: ‘NVPW_MetricsEvaluator_SetDeviceAttributes’ was not declared in this scope
  730 |       nvpw_call(NVPW_MetricsEvaluator_SetDeviceAttributes(&params));
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:734:7: error: ‘NVPW_MetricsEvaluator_EvaluateToGpuValues_Params’ was not declared in this scope; did you mean ‘NVPW_MetricsContext_EvaluateToGpuValues_Params’?
  734 |       NVPW_MetricsEvaluator_EvaluateToGpuValues_Params params{};
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |       NVPW_MetricsContext_EvaluateToGpuValues_Params
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:736:7: error: ‘params’ was not declared in this scope
  736 |       params.structSize            = NVPW_MetricsEvaluator_EvaluateToGpuValues_Params_STRUCT_SIZE;
      |       ^~~~~~
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:736:38: error: ‘NVPW_MetricsEvaluator_EvaluateToGpuValues_Params_STRUCT_SIZE’ was not declared in this scope; did you mean ‘NVPW_MetricsContext_EvaluateToGpuValues_Params_STRUCT_SIZE’?
  736 |       params.structSize            = NVPW_MetricsEvaluator_EvaluateToGpuValues_Params_STRUCT_SIZE;
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                      NVPW_MetricsContext_EvaluateToGpuValues_Params_STRUCT_SIZE
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:738:47: error: ‘class nvbench::detail::{anonymous}::eval_request’ has no member named ‘request’
  738 |       params.pMetricEvalRequests   = &request.request;
      |                                               ^~~~~~~
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:740:44: error: ‘NVPW_MetricEvalRequest_STRUCT_SIZE’ was not declared in this scope
  740 |       params.metricEvalRequestStructSize = NVPW_MetricEvalRequest_STRUCT_SIZE;
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:741:51: error: ‘NVPW_MetricEvalRequest’ was not declared in this scope
  741 |       params.metricEvalRequestStrideSize = sizeof(NVPW_MetricEvalRequest);
      |                                                   ^~~~~~~~~~~~~~~~~~~~~~
/home/hao/nvbench-git/nvbench/nvbench/cupti_profiler.cxx:748:17: error: ‘NVPW_MetricsEvaluator_EvaluateToGpuValues’ was not declared in this scope; did you mean ‘NVPW_MetricsContext_EvaluateToGpuValues’?
  748 |       nvpw_call(NVPW_MetricsEvaluator_EvaluateToGpuValues(&params));
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                 NVPW_MetricsContext_EvaluateToGpuValues
make[2]: *** [nvbench/CMakeFiles/nvbench.dir/build.make:426: nvbench/CMakeFiles/nvbench.dir/cupti_profiler.cxx.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:272: nvbench/CMakeFiles/nvbench.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by ax7e** [comment]
It's seem that it's anaconda environment's problem. 
solved by
'~/anaconda3/envs/YOUR_ENV_NAME/include$ cp ../pkgs/cuda-toolkit/extras/CUPTI/include/* ./'
